export const permissionsData = [
  // Employee permissions
  {
    resource: 'employee',
    action: 'create',
    scope: 'all',
    displayName: 'Create Employee',
    description: 'Create new employees',
  },
  {
    resource: 'employee',
    action: 'read',
    scope: 'own',
    displayName: 'Read Own Profile',
    description: 'View own employee profile',
  },
  {
    resource: 'employee',
    action: 'read',
    scope: 'department',
    displayName: 'Read Department Employees',
    description: 'View employees in same department',
  },
  {
    resource: 'employee',
    action: 'read',
    scope: 'all',
    displayName: 'Read All Employees',
    description: 'View all employee profiles',
  },
  {
    resource: 'employee',
    action: 'update',
    scope: 'own',
    displayName: 'Update Own Profile',
    description: 'Update own employee profile',
  },
  {
    resource: 'employee',
    action: 'update',
    scope: 'all',
    displayName: 'Update Any Employee',
    description: 'Update any employee profile',
  },
  {
    resource: 'employee',
    action: 'delete',
    scope: 'all',
    displayName: 'Delete Employee',
    description: 'Delete employee records',
  },
  {
    resource: 'employee',
    action: 'export',
    scope: 'all',
    displayName: 'Export Employees',
    description: 'Export employee data',
  },

  // Attendance permissions
  {
    resource: 'attendance',
    action: 'create',
    scope: 'own',
    displayName: 'Clock In/Out',
    description: 'Record own attendance',
  },
  {
    resource: 'attendance',
    action: 'read',
    scope: 'own',
    displayName: 'View Own Attendance',
    description: 'View own attendance records',
  },
  {
    resource: 'attendance',
    action: 'read',
    scope: 'department',
    displayName: 'View Department Attendance',
    description: 'View department attendance',
  },
  {
    resource: 'attendance',
    action: 'read',
    scope: 'all',
    displayName: 'View All Attendance',
    description: 'View all attendance records',
  },
  {
    resource: 'attendance',
    action: 'update',
    scope: 'all',
    displayName: 'Update Attendance',
    description: 'Modify attendance records',
  },
  {
    resource: 'attendance',
    action: 'approve',
    scope: 'department',
    displayName: 'Approve Department Overtime',
    description: 'Approve overtime in department',
  },
  {
    resource: 'attendance',
    action: 'export',
    scope: 'all',
    displayName: 'Export Attendance',
    description: 'Export attendance data',
  },

  // Leave permissions
  {
    resource: 'leave',
    action: 'create',
    scope: 'own',
    displayName: 'Request Leave',
    description: 'Submit leave requests',
  },
  {
    resource: 'leave',
    action: 'read',
    scope: 'own',
    displayName: 'View Own Leaves',
    description: 'View own leave records',
  },
  {
    resource: 'leave',
    action: 'read',
    scope: 'department',
    displayName: 'View Department Leaves',
    description: 'View department leave requests',
  },
  {
    resource: 'leave',
    action: 'read',
    scope: 'all',
    displayName: 'View All Leaves',
    description: 'View all leave records',
  },
  {
    resource: 'leave',
    action: 'approve',
    scope: 'department',
    displayName: 'Approve Department Leaves',
    description: 'Approve leaves in department',
  },
  {
    resource: 'leave',
    action: 'approve',
    scope: 'all',
    displayName: 'Approve Any Leave',
    description: 'Approve any leave request',
  },
  {
    resource: 'leave',
    action: 'reject',
    scope: 'department',
    displayName: 'Reject Department Leaves',
    description: 'Reject leaves in department',
  },
  {
    resource: 'leave',
    action: 'reject',
    scope: 'all',
    displayName: 'Reject Any Leave',
    description: 'Reject any leave request',
  },
  {
    resource: 'leave',
    action: 'update',
    scope: 'all',
    displayName: 'Update Leave',
    description: 'Modify leave records',
  },

  // Payroll permissions
  {
    resource: 'payroll',
    action: 'read',
    scope: 'own',
    displayName: 'View Own Payslip',
    description: 'View own salary and payslips',
  },
  {
    resource: 'payroll',
    action: 'read',
    scope: 'all',
    displayName: 'View All Payroll',
    description: 'View all salary information',
  },
  {
    resource: 'payroll',
    action: 'create',
    scope: 'all',
    displayName: 'Process Payroll',
    description: 'Run payroll processing',
  },
  {
    resource: 'payroll',
    action: 'update',
    scope: 'all',
    displayName: 'Update Payroll',
    description: 'Modify payroll records',
  },
  {
    resource: 'payroll',
    action: 'export',
    scope: 'all',
    displayName: 'Export Payroll',
    description: 'Export payroll data',
  },

  // Notification permissions
  {
    resource: 'notification',
    action: 'read',
    scope: 'own',
    displayName: 'View Own Notifications',
    description: 'View own notifications',
  },
  {
    resource: 'notification',
    action: 'create',
    scope: 'all',
    displayName: 'Send Notifications',
    description: 'Send system notifications',
  },

  // Role management permissions
  {
    resource: 'role',
    action: 'create',
    scope: 'all',
    displayName: 'Create Role',
    description: 'Create new roles',
  },
  {
    resource: 'role',
    action: 'read',
    scope: 'all',
    displayName: 'View Roles',
    description: 'View all roles',
  },
  {
    resource: 'role',
    action: 'update',
    scope: 'all',
    displayName: 'Update Role',
    description: 'Modify role settings',
  },
  {
    resource: 'role',
    action: 'delete',
    scope: 'all',
    displayName: 'Delete Role',
    description: 'Delete roles',
  },
  {
    resource: 'role',
    action: 'assign',
    scope: 'all',
    displayName: 'Assign Roles',
    description: 'Assign roles to users',
  },

  // Permission management
  {
    resource: 'permission',
    action: 'read',
    scope: 'all',
    displayName: 'View Permissions',
    description: 'View all permissions',
  },
  {
    resource: 'permission',
    action: 'create',
    scope: 'all',
    displayName: 'Create Permission',
    description: 'Create new permissions',
  },

  // User management
  {
    resource: 'user',
    action: 'read',
    scope: 'all',
    displayName: 'View Users',
    description: 'View all user accounts',
  },
  {
    resource: 'user',
    action: 'update',
    scope: 'all',
    displayName: 'Update User',
    description: 'Modify user accounts',
  },
  {
    resource: 'user',
    action: 'delete',
    scope: 'all',
    displayName: 'Delete User',
    description: 'Delete user accounts',
  },
];

export const hrAdminPermissions = [
  'employee:create:all',
  'employee:read:all',
  'employee:update:all',
  'employee:export:all',
  'attendance:read:all',
  'attendance:update:all',
  'attendance:approve:department',
  'attendance:export:all',
  'leave:read:all',
  'leave:approve:all',
  'leave:reject:all',
  'leave:update:all',
  'payroll:read:all',
  'payroll:create:all',
  'payroll:update:all',
  'payroll:export:all',
  'notification:create:all',
  'user:read:all',
];

export const managerPermissions = [
  'employee:read:department',
  'attendance:read:department',
  'attendance:approve:department',
  'leave:read:department',
  'leave:approve:department',
  'leave:reject:department',
];

export const employeePermissions = [
  'employee:read:own',
  'employee:update:own',
  'attendance:create:own',
  'attendance:read:own',
  'leave:create:own',
  'leave:read:own',
  'payroll:read:own',
  'notification:read:own',
];
